### ISSUE TITLE
Wire.requestFrom() should not be followed by Wire.endTransmission().

### ISSUE THREAD

**Issue by Koepel** [chrisxkeith/ir-qwwic-example#1]
In the file "ir-qwiic-example.ino", in the function `getRegister()`, there is a `Wire.endTransmission()` after a `Wire.requestFrom()`. You may remove the `Wire.endTransmission()` at the end of the function, currently at line 1018.
Explanation: [Common-mistakes#2](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#2)

**Comment by chrisxkeith** [comment]
Thank you for letting me know. I have changed my copy of the code.

I got this code from https://learn.sparkfun.com/tutorials/qwiic-grid-eye-infrared-array-amg88xx-hookup-guide , and modified it for the Particle Proton.

Do you know if there is any way to tell Sparkfun to update their example code?

Thanks again for your help!

**Comment by Koepel** [comment]
Thanks for telling me that Sparkfun made a mistake even this year! I have made an issue here: https://github.com/sparkfun/SparkFun_GridEYE_Arduino_Library/issues/3
Some companies are too busy to fix existing libraries. They don't care a minor bug, as long as it works (more or less).
